### ISSUE TITLE
retract v0.3.2 of this module

### ISSUE THREAD

**Issue by fzipp** [go-fonts/dejavu#2]
The module proxy sees v0.3.2 as the latest version https://pkg.go.dev/github.com/go-fonts/dejavu@v0.3.2 but it does not exist anymore, so it should be [retracted](https://go.dev/ref/mod#go-mod-file-retract).

**Comment by sbinet** [comment]
actually, it's probably a finger problem from my end when I bulk-updated the `go-fonts` packages for the `x.image@v0.13.0` patch version.

sorry about that.
(I've published v0.3.2 and v0.3.3)
